export const NO_DATA_AVAILABLE = 'No data available';
export const COUNTRIES = 'countries';
export const AUTHORS = 'authors';
export const BOOKS = 'books';
export const NO_AUTHOR_INFORMATION = 'No author information available';
export const ERROR_FETCHING_DATA = 'Error fetching data';
export const NO_NAME = 'No Name Available';
export const BEST_SELLING_BOOKS = 'Best-selling books';
export const PRIMARY_URL_FAIL = 'Primary URL failed';
export const BOOK_NOT_FOUND = "Book with ID {id} not found in included data.";
export const STAR_FILLED = '★'
export const STAR_EMPTY = '☆'